### ISSUE TITLE
Can not run 'digitRecognition' code

### ISSUE THREAD

**Issue by ananno** [iraihankabir/DeepLearning#6]
While running `digitRecognition` code I'm getting this error:
```
Connected to pydev debugger (build 182.4129.34)
Traceback (most recent call last):
  File "/home/hasibur/Applications/pycharm-2018.1.4/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/hasibur/Applications/pycharm-2018.1.4/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/hasibur/Applications/pycharm-2018.1.4/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/hasibur/Applications/pycharm-2018.1.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/hasibur/Projects/RK_DL/digitRecognition/network.py", line 3, in <module>
    from datasets import Dataset
  File "/home/hasibur/Projects/RK_DL/digitRecognition/datasets.py", line 1, in <module>
    from mlxtend.data import loadlocal_mnist
ModuleNotFoundError: No module named 'mlxtend'

Process finished with exit code 1
```

**Comment by iraihankabir** [comment]
Install the package... mlxtend
`pip install mlxtend`

**Comment by ananno** [comment]
@iraihankabir : Add a requirement.txt file in the repository. Read about requirement file in python project.

**Comment by iraihankabir** [comment]
added requirement.txt [here](https://github.com/iraihankabir/DeepLearning/tree/master/digitRecognition)
